name: superq2
channels:
  - gurobi
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.3=py312h78d62e6_4
  - cycler=0.12.1=pyhcf101f3_2
  - double-conversion=3.3.1=he0c23c2_0
  - expat=2.7.4=hd7fb8db_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=hd211d86_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h05f76fc_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - gurobi=13.0.1=py312_0
  - harfbuzz=12.2.0=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - intel-openmp=2025.0.0=haa95532_1164
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libclang13=21.1.8=default_ha2db4b5_3
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libglib=2.86.3=h9bccc14_0
  - libgomp=15.2.0=h8ee18e1_17
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libpng=1.6.54=h7351971_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=2.4.1=py312h050da96_0
  - numpy-base=2.4.1=py312h1e017a8_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py312haa95532_1
  - pcre2=10.46=h3402e2f_0
  - pillow=11.3.0=py312h5ee8bfe_3
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.9.2=py312h0ba07f7_1
  - python=3.12.3=h1d929f7_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=3_cp312
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.2=ha0de62e_2
  - setuptools=80.10.2=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py312he06e257_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py312he06e257_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py312haa95532_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
prefix: D:\apps\anaconda\envs\superq
